name       : onefetch
version    : 2.9.1
release    : 3
source     :
    - https://github.com/o2sh/onefetch/archive/v2.9.1.tar.gz : 33ac8e019e5b7412fec3c7593843e0c3780ca473498c31e36cbe95371fff943b
license    : MIT
component  : system.utils
networking : yes
summary    : A command-line Git information tool written in Rust
description: |
    Onefetch is a command-line Git information tool written in Rust that will display project information and code statistics about your Git repository directly on your terminal.
builddeps  :
    - cargo
build      : |
    cargo build --release
install    : |
    install -Dm00755 target/release/onefetch $installdir/usr/bin/onefetch
    install -Dm00644 docs/onefetch.1 $installdir/usr/share/man/man1/onefetch.1
check      : |
    cargo test --all
